### PR TITLE
GDALDataset Error Reporting

### LINKED ISSUE #179: Improve error reporting in GDALDataset
Reporting of errors from the JNI bindings could easily be improved. Currently they take the form of:

https://github.com/geotrellis/geotrellis-contrib/blob/94ccdebff8ce58f5f3d8e1f96046961bb6ba1a46/gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala#L148

 in the following ways:

1. Don't throw top-level `Exception`, but something more "filterable", such as `IOException`, `ConnectException` or a new custom `GDALException`.
2. Setting the message to be the name of the JNI method doesn't provide enough information to figure out what happened. First order would be to include the integer error code.
3. Even better would be to convert the error code via a lookup table into something user interpretable. e.g. "403 authorization error".

### LINKED ISSUE #215: Expose GDAL Error codes
It is a logical extension of the https://github.com/geotrellis/geotrellis-contrib/issues/179 

Exceptions that were added by closing https://github.com/geotrellis/geotrellis-contrib/issues/179 should also include error codes. By the time of creating this issue GDAL Warp bindings doesn't expose the underlying GDAL message and / or code: 

Example by @jbouffard:

```scala
scala> GDALWarp.get_band_count(token, GDALWarp.WARPED, numberOfAttempts, count)
ERROR 4: ../../blah.tif: No such file or directory
res5: Int = -1
```

Reference by @metasim about what do we mean here by [error codes](https://joinup.ec.europa.eu/svn/gvsig-3d/1.10/trunk/binaries/mac/raster/gdal/GDAL.framework/Versions/1.7/Resources/doc/gdal/cpl__error_8h.html). 

A related GDALWarpBindings issue: https://github.com/geotrellis/gdal-warp-bindings/issues/52

### PR DESCRIPTION
**Pull request by jbouffard**
# Overview

This PR changes the exceptions thrown in `GDALDataset` to be instances of a new `Exception` class `GDALException`. These new exceptions will provide more helpful information as to why a certain operation failed when reading in data with GDAL. The new class `GDALException` was created to allow users to more easily filter exceptions that are and are not GDAL related.

## Notes

This PR does not return error codes as there is currently no way to determine which one was thrown on the GDAL side. However, once https://github.com/geotrellis/gdal-warp-bindings/issues/52 is resolved, we'll be able to supply error codes along with the message.

## Checklist

- [x] Add entry to CHANGELOG.md

Closes #179 
Closes #215

### CODE REVIEW

**Comment by pomadchin** [comment]
Would also like to hear @metasim opinion on that, since he is the initial author of that and user of our VLM API

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala [hunk 1]
```diff
@@ -42,7 +42,7 @@ case class GDALDataset(token: Long) extends AnyVal {
     val width_height = Array.ofDim[Int](2)
     if (GDALWarp.get_transform(token, dataset, numberOfAttempts, transform) <= 0 ||
       GDALWarp.get_width_height(token, dataset, numberOfAttempts, width_height) <= 0)
-      throw new Exception("get_transform or get_width_height")
+      throw new MalformedDataException("Bad tranform values read")
```
Comment (pomadchin) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: Can you think of a better exception messages? In this case it looks like it can't construct `RasterExtent`.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala [hunk 2]
```diff
@@ -68,7 +68,7 @@ case class GDALDataset(token: Long) extends AnyVal {
     val extent = this.extent(dataset)
 
     if (GDALWarp.get_overview_widths_heights(token, dataset, numberOfAttempts, 1, widths, heights) <= 0)
-      throw new Exception("get_overview_widths_heights")
+      throw new MalformedDataException("Unable to read in overviews")
```
Comment (pomadchin) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: It can not construct overivew `RasterExtents`. Mb it is better to throw an exception that would explain the issue cause in terms of the entire function definition?

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala [hunk 3]
```diff
@@ -145,7 +145,7 @@ case class GDALDataset(token: Long) extends AnyVal {
       val minmax = Array.ofDim[Double](2)
       val success = Array.ofDim[Int](1)
       if (GDALWarp.get_band_min_max(token, dataset, numberOfAttempts, 1, true, minmax, success) <= 0)
-        throw new Exception("get_band_min_max")
+        throw new MalformedDataTypeException("Bad min/max values")
```
Comment (pomadchin) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: What is the difference between `unable` and `bad` words you use in different exceptions?

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package geotrellis.contrib.vlm.gdal
+
+
+/** Base class for all Exceptions involving GDAL. */
+class GDALException(message: String) extends Exception(message)
```
Comment (pomadchin) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: Should it be a `RuntimeException` like in `geotrellis-gdal`? I don't have a strong opinion about that btw.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala [hunk 5]
```diff
@@ -42,7 +42,7 @@ case class GDALDataset(token: Long) extends AnyVal {
     val width_height = Array.ofDim[Int](2)
     if (GDALWarp.get_transform(token, dataset, numberOfAttempts, transform) <= 0 ||
       GDALWarp.get_width_height(token, dataset, numberOfAttempts, width_height) <= 0)
```
Comment (metasim) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: What are the possible values and semantics of the value returned integer value? If it can return values other than zero and one, I'd propose having the code included in the exception message so we can at least go look it up in the GDAL docs. We were getting errors thrown here that were due to S3 authentication errors, but at first it looked like there was a data error. Error codes could help ameliorate this.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala (hunk 4 above)
Comment (metasim) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: @pomadchin `RuntimeException` should only be used for _unchecked_ exceptions (in a Java sense). While all exceptions in Scala are unchecked, I'd suggest following the general intent, and keeping `Exception` as the base type.

> RuntimeException is the superclass of those exceptions that can be thrown during the normal operation of the Java Virtual Machine.
> RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor's throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+
+/** Exception thrown when data coulld not be read from data source. */
+class GDALIOException(message: String) extends Exception(message)
```
Comment (metasim) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: I suggest making this a subtype of `IOException`. 

Also: "coulld".

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala (hunk 4 above)
Comment (metasim) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: That said.... I could see debates on both side of the issue, so I wouldn't fight over my position ;-)

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala (hunk 5 above)
Comment (metasim) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: Yeh, according to [this](https://github.com/geotrellis/gdal-warp-bindings/blob/58d496521695b4bae2b7f7ab7d1f17140be0a569/src/bindings.cpp#L511-L512) the return value has some sort of meaning one could inspect for debugging.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala (hunk 4 above)
Comment (metasim) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: Another  consideration, assuming all these exceptions are raised when getting error codes from the underlying GDAL library, is to have a field called `gdal_error_code` to capture the value returned.

Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: @metasim yea in Scala all exceptions are unchecked, but I was just curious does it make too much sense to follow Java logic or not (like MalformedArgument exceptions, etc). But I see your comment about IO and I'm good with keeping it `<: Exception`

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala (hunk 3 above)
Comment (jbouffard) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: Really the only difference is that the `Unable` implies that something is `bad`. However, I think it'd be better if we tried to standardized the messages more, so I'll change them to one phrasing.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala (hunk 5 above)
Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: @metasim I think it returns a number of the datasets that `GDALWarp.method` touched to return a value requested from by the `method`. As @jamesmcclain mentioned right now, that the idea was that probably it would be possible to use this information in some dynamic performance tuning. There is an issue https://github.com/geotrellis/gdal-warp-bindings/issues/52 about it.

Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: wooops @metasim mb you're right; @jbouffard can you check that it returns GDAL error codes? As it can return smth internal?

Comment (jbouffard) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: @pomadchin Do you have any malformed GeoTiffs? I don't think I have anything that would fail to be read

Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: @jbouffard you can point to a non existent file or to a file that is not a geotiff though have a `.tiff` extension

Comment (jbouffard) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: @pomadchin @metasim This is what's returned when trying to read a bad file with GDAL:

```
scala> GDALWarp.get_band_count(token, GDALWarp.WARPED, numberOfAttempts, count)
ERROR 4: ../../blah.tif: No such file or directory
res5: Int = -1
```

So while he `ERROR` message shown is correct, the return of `-1` is not.

Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: @jbouffard it looks like the only thing we can do in this case is to return to this problem, once it would be addressed in bindings. The best thing we can do now is to write our messages without codes, since it is impossible to retrieve that information from the native interface now.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala (hunk 4 above)
Comment (jbouffard) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: This is something that should be added once the return value reflects the number of the error thrown.

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala [hunk 7]
```diff
@@ -68,7 +68,7 @@ case class GDALDataset(token: Long) extends AnyVal {
     val extent = this.extent(dataset)
 
     if (GDALWarp.get_overview_widths_heights(token, dataset, numberOfAttempts, 1, widths, heights) <= 0)
-      throw new Exception("get_overview_widths_heights")
+      throw new MalformedDataException("Unable to construct overviews for resample")
```
Comment (pomadchin) [inline gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala]: just a minor thing, mb contruct `overviews RasterExtents` (pr smth in a better language)? Since here we don't construct overviews, just overviews `RasterExtents`.

**Comment by pomadchin** [comment]
Also created a follow up issue https://github.com/geotrellis/geotrellis-contrib/issues/215 that would be a separate small once, since it can not be done at the moment in terms of this PR.

**Comment by jamesmcclain** [comment]
In progress https://github.com/geotrellis/gdal-warp-bindings/pull/56

**Comment by pomadchin** [comment]
@jbouffard let's wait for a little bit? mb @jamesmcclain will release a new bindings version soon

**Comment by jbouffard** [comment]
@pomadchin I was thinking that as well. No sense in creating another PR right after this one.

**Comment by pomadchin** [comment]
@jbouffard James published already a new release! https://github.com/geotrellis/gdal-warp-bindings/pull/56

File: gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala (hunk 4 above)
Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALException.scala]: @jbouffard I think this comment is still unaddressed.

File: gdal/src/test/scala/geotrellis/contrib/vlm/gdal/GDALErrorSpec.scala [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+
+  describe("GDALErrors") {
+    it("should return the ObjectNull error code") {
+      val result = GDALWarp.get_data(token, dataset, 1, sourceWindow, destWindow, 42, 1, buffer)
+
+      assert(math.abs(result) == 10)
+    }
+
+    it("should return the IllegalArg error code") {
+      val result = GDALWarp.get_data(token, dataset, 1, sourceWindow, destWindow, 1, 1, buffer)
```
Comment (pomadchin) [inline gdal/src/test/scala/geotrellis/contrib/vlm/gdal/GDALErrorSpec.scala]: Nice that it works! The only thing that needs to be done is to pass these error codes into our Exception types.
